# Generated by Django 6.0.2 on 2026-06-21 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_alter_merma_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merma',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='merma',
            name='motivo',
            field=models.CharField(choices=[('VENCIDO', 'Producto Vencido / Caducado'), ('DANO_FISICO', 'Daño Físico / Rotura de empaque'), ('MAL_ESTADO', 'Mal Estado / Descomposición'), ('CONTEO', 'Discrepancia en Conteo'), ('OTRO', 'Otro (Especificar en observaciones)')], max_length=50),
        ),
    ]
