# Generated by Django 6.0.2 on 2026-06-21 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_alter_producto_unidad_medida'),
        ('ventas', '0002_detalle_pedido_presentacion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Detalle_Pedido',
            new_name='DetallePedido',
        ),
        migrations.RenameModel(
            old_name='Evidencia_Entrega',
            new_name='EvidenciaEntrega',
        ),
    ]
