# Generated by Django 6.0.2 on 2026-06-21 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_carritoitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='unidad_medida',
            field=models.CharField(choices=[('lb', 'Libra (lb)'), ('kg', 'Kilogramo (kg)'), ('und', 'Unidad (und)'), ('atado', 'Atado'), ('500g', '500 gramos'), ('250g', '250 gramos')], default='lb', max_length=10),
        ),
    ]
